# Generated by Django 3.2 on 2022-04-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
